// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID              pgtype.UUID      `json:"id"`
	Url             string           `json:"url"`
	IntervalSeconds int32            `json:"interval_seconds"`
	IsActive        bool             `json:"is_active"`
	LastCheck       pgtype.Timestamp `json:"last_check"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type MonitorResult struct {
	ID             pgtype.UUID      `json:"id"`
	MonitorID      pgtype.UUID      `json:"monitor_id"`
	StatusCode     int32            `json:"status_code"`
	Status         string           `json:"status"`
	Latency        int32            `json:"latency"`
	TimingDns      int32            `json:"timing_dns"`
	TimingTcp      int32            `json:"timing_tcp"`
	TimingTls      int32            `json:"timing_tls"`
	TimingTtfb     int32            `json:"timing_ttfb"`
	TimingDownload int32            `json:"timing_download"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type SystemStat struct {
	ID              pgtype.UUID        `json:"id"`
	CpuPercent      float64            `json:"cpu_percent"`
	MemoryPercent   float64            `json:"memory_percent"`
	DiskPercent     float64            `json:"disk_percent"`
	NetKbS          float64            `json:"net_kb_s"`
	ThreadsTotal    int32              `json:"threads_total"`
	ThreadsRunning  int32              `json:"threads_running"`
	ThreadsSleeping int32              `json:"threads_sleeping"`
	ThreadsZombie   int32              `json:"threads_zombie"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
