// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanOldMonitorResults = `-- name: CleanOldMonitorResults :exec
DELETE FROM monitor_results
WHERE created_at < NOW() - INTERVAL '7 days'
`

// 7 günden eski verileri siler (DB şişmesin diye)
func (q *Queries) CleanOldMonitorResults(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanOldMonitorResults)
	return err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (url, interval_seconds)
VALUES ($1, $2)
RETURNING id, url, interval_seconds, is_active, last_check, created_at
`

type CreateMonitorParams struct {
	Url             string `json:"url"`
	IntervalSeconds int32  `json:"interval_seconds"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor, arg.Url, arg.IntervalSeconds)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IntervalSeconds,
		&i.IsActive,
		&i.LastCheck,
		&i.CreatedAt,
	)
	return i, err
}

const createMonitorResult = `-- name: CreateMonitorResult :one

INSERT INTO monitor_results (
    id,
    monitor_id,
    status_code,
    status,
    latency,
    timing_dns,
    timing_tcp,
    timing_tls,
    timing_ttfb,
    timing_download,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW()
) RETURNING id, monitor_id, status_code, status, latency, timing_dns, timing_tcp, timing_tls, timing_ttfb, timing_download, created_at
`

type CreateMonitorResultParams struct {
	ID             pgtype.UUID `json:"id"`
	MonitorID      pgtype.UUID `json:"monitor_id"`
	StatusCode     int32       `json:"status_code"`
	Status         string      `json:"status"`
	Latency        int32       `json:"latency"`
	TimingDns      int32       `json:"timing_dns"`
	TimingTcp      int32       `json:"timing_tcp"`
	TimingTls      int32       `json:"timing_tls"`
	TimingTtfb     int32       `json:"timing_ttfb"`
	TimingDownload int32       `json:"timing_download"`
}

// --- YENİ EKLENENLER (History için) ---
func (q *Queries) CreateMonitorResult(ctx context.Context, arg CreateMonitorResultParams) (MonitorResult, error) {
	row := q.db.QueryRow(ctx, createMonitorResult,
		arg.ID,
		arg.MonitorID,
		arg.StatusCode,
		arg.Status,
		arg.Latency,
		arg.TimingDns,
		arg.TimingTcp,
		arg.TimingTls,
		arg.TimingTtfb,
		arg.TimingDownload,
	)
	var i MonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StatusCode,
		&i.Status,
		&i.Latency,
		&i.TimingDns,
		&i.TimingTcp,
		&i.TimingTls,
		&i.TimingTtfb,
		&i.TimingDownload,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const getMonitorResults = `-- name: GetMonitorResults :many
SELECT id, monitor_id, status_code, status, latency, timing_dns, timing_tcp, timing_tls, timing_ttfb, timing_download, created_at FROM monitor_results
WHERE monitor_id = $1
ORDER BY created_at DESC
LIMIT 50
`

// Bir monitörün son 50 kaydını getirir (Grafik için)
func (q *Queries) GetMonitorResults(ctx context.Context, monitorID pgtype.UUID) ([]MonitorResult, error) {
	rows, err := q.db.Query(ctx, getMonitorResults, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonitorResult
	for rows.Next() {
		var i MonitorResult
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StatusCode,
			&i.Status,
			&i.Latency,
			&i.TimingDns,
			&i.TimingTcp,
			&i.TimingTls,
			&i.TimingTtfb,
			&i.TimingDownload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonitorsToPing = `-- name: GetMonitorsToPing :many
SELECT id, url, interval_seconds, is_active, last_check, created_at FROM monitors
WHERE is_active = true 
AND (last_check IS NULL OR last_check < NOW() - (interval_seconds || ' seconds')::INTERVAL)
`

// Kontrol zamanı gelmiş (veya hiç kontrol edilmemiş) aktif monitörleri getir
func (q *Queries) GetMonitorsToPing(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, getMonitorsToPing)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSeconds,
			&i.IsActive,
			&i.LastCheck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, url, interval_seconds, is_active, last_check, created_at FROM monitors
ORDER BY created_at DESC
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSeconds,
			&i.IsActive,
			&i.LastCheck,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitorLastCheck = `-- name: UpdateMonitorLastCheck :exec
UPDATE monitors
SET last_check = NOW()
WHERE id = $1
`

func (q *Queries) UpdateMonitorLastCheck(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateMonitorLastCheck, id)
	return err
}
