// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// 7 günden eski verileri siler (DB şişmesin diye)
	CleanOldMonitorResults(ctx context.Context) error
	// Grafik daha geniş görünsün diye 100 yaptık
	// Veriyi 6 ay sakla (Best Practice: Uzun dönem analiz için)
	CleanOldSystemStats(ctx context.Context) error
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	// --- YENİ EKLENENLER (History için) ---
	CreateMonitorResult(ctx context.Context, arg CreateMonitorResultParams) (MonitorResult, error)
	CreateSystemStat(ctx context.Context, arg CreateSystemStatParams) (SystemStat, error)
	DeleteMonitor(ctx context.Context, id pgtype.UUID) error
	// Bir monitörün son 50 kaydını getirir (Grafik için)
	GetMonitorResults(ctx context.Context, monitorID pgtype.UUID) ([]MonitorResult, error)
	// Kontrol zamanı gelmiş (veya hiç kontrol edilmemiş) aktif monitörleri getir
	GetMonitorsToPing(ctx context.Context) ([]Monitor, error)
	GetSystemStatHistory(ctx context.Context) ([]SystemStat, error)
	ListMonitors(ctx context.Context) ([]Monitor, error)
	UpdateMonitorLastCheck(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
