// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system.sql

package db

import (
	"context"
)

const cleanOldSystemStats = `-- name: CleanOldSystemStats :exec

DELETE FROM system_stats
WHERE created_at < NOW() - INTERVAL '6 months'
`

// Grafik daha geniş görünsün diye 100 yaptık
// Veriyi 6 ay sakla (Best Practice: Uzun dönem analiz için)
func (q *Queries) CleanOldSystemStats(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanOldSystemStats)
	return err
}

const createSystemStat = `-- name: CreateSystemStat :one
INSERT INTO system_stats (
    cpu_percent, 
    memory_percent, 
    disk_percent, 
    net_kb_s,
    threads_total,
    threads_running,
    threads_sleeping,
    threads_zombie
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, cpu_percent, memory_percent, disk_percent, net_kb_s, threads_total, threads_running, threads_sleeping, threads_zombie, created_at
`

type CreateSystemStatParams struct {
	CpuPercent      float64 `json:"cpu_percent"`
	MemoryPercent   float64 `json:"memory_percent"`
	DiskPercent     float64 `json:"disk_percent"`
	NetKbS          float64 `json:"net_kb_s"`
	ThreadsTotal    int32   `json:"threads_total"`
	ThreadsRunning  int32   `json:"threads_running"`
	ThreadsSleeping int32   `json:"threads_sleeping"`
	ThreadsZombie   int32   `json:"threads_zombie"`
}

func (q *Queries) CreateSystemStat(ctx context.Context, arg CreateSystemStatParams) (SystemStat, error) {
	row := q.db.QueryRow(ctx, createSystemStat,
		arg.CpuPercent,
		arg.MemoryPercent,
		arg.DiskPercent,
		arg.NetKbS,
		arg.ThreadsTotal,
		arg.ThreadsRunning,
		arg.ThreadsSleeping,
		arg.ThreadsZombie,
	)
	var i SystemStat
	err := row.Scan(
		&i.ID,
		&i.CpuPercent,
		&i.MemoryPercent,
		&i.DiskPercent,
		&i.NetKbS,
		&i.ThreadsTotal,
		&i.ThreadsRunning,
		&i.ThreadsSleeping,
		&i.ThreadsZombie,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemStatHistory = `-- name: GetSystemStatHistory :many
SELECT id, cpu_percent, memory_percent, disk_percent, net_kb_s, threads_total, threads_running, threads_sleeping, threads_zombie, created_at FROM system_stats
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetSystemStatHistory(ctx context.Context) ([]SystemStat, error) {
	rows, err := q.db.Query(ctx, getSystemStatHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemStat
	for rows.Next() {
		var i SystemStat
		if err := rows.Scan(
			&i.ID,
			&i.CpuPercent,
			&i.MemoryPercent,
			&i.DiskPercent,
			&i.NetKbS,
			&i.ThreadsTotal,
			&i.ThreadsRunning,
			&i.ThreadsSleeping,
			&i.ThreadsZombie,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
